# Generated by Django 4.2 on 2023-04-09 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Afectacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('afectacion', models.CharField(max_length=80)),
                ('descripcion', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Barrver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('nomcomun', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Cez',
            fields=[
                ('codigo', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Cobertura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cobertura', models.CharField(max_length=40)),
                ('peso', models.FloatField()),
                ('descripcion', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Comcorr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Deslizamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipodeslizam', models.CharField(max_length=80)),
                ('peso', models.FloatField()),
                ('descripcion', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='ElemExpuestos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elemexpuestos', models.CharField(max_length=80)),
                ('peso', models.FloatField()),
                ('descripcion', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Erosion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoerosion', models.CharField(max_length=80)),
                ('peso', models.FloatField()),
                ('descripcion', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='FactoresContr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fcontribuyente', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='FactoresDeton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fdetonante', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Freatico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.CharField(max_length=40)),
                ('peso', models.FloatField()),
                ('descripcion', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Geologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad', models.CharField(max_length=40)),
                ('peso', models.FloatField()),
                ('leyenda', models.CharField(max_length=120)),
                ('descripcion', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Litologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad', models.CharField(max_length=120)),
                ('peso', models.FloatField()),
                ('leyenda', models.CharField(max_length=120)),
                ('descripcion', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Obras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obra', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Pendiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rango', models.CharField(max_length=40)),
                ('categoria', models.CharField(max_length=40)),
                ('peso', models.FloatField()),
                ('descripcion', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('identificacion', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=40)),
                ('apellido1', models.CharField(max_length=40)),
                ('apellido2', models.CharField(max_length=40)),
                ('telefono', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='PersonaDiger',
            fields=[
                ('identificacion', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=40)),
                ('apellido1', models.CharField(max_length=40)),
                ('apellido2', models.CharField(max_length=40)),
                ('telefono', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Psicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psico', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Taludes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=120)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('largo', models.FloatField()),
                ('alto', models.FloatField()),
                ('observaciones', models.CharField(verbose_name=500)),
                ('foto1', models.URLField(max_length=500)),
                ('foto2', models.URLField(max_length=500)),
                ('foto3', models.URLField(max_length=500)),
                ('url_datos', models.URLField(max_length=500)),
                ('barrver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.barrver')),
                ('cez', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.cez')),
                ('comcorr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.comcorr')),
                ('geologia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.geologia')),
                ('litologia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.litologia')),
                ('pendiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.pendiente')),
                ('persocontacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.persona')),
            ],
        ),
        migrations.CreateModel(
            name='TipoActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.CharField(max_length=40)),
                ('peso', models.FloatField()),
                ('descripcion', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='TipoClima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clima', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='TipoProceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='TipoTalud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='VisitasTalud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('observaciones', models.CharField(verbose_name=500)),
                ('foto1', models.URLField(max_length=500)),
                ('foto2', models.URLField(max_length=500)),
                ('foto3', models.URLField(max_length=500)),
                ('TipoProceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.tipoproceso')),
                ('afectacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.afectacion')),
                ('clima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.tipoclima')),
                ('cobersuelo', models.ManyToManyField(to='Gestion.cobertura')),
                ('contribuyente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.factorescontr')),
                ('detonante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.factoresdeton')),
                ('elemexpuestos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.elemexpuestos')),
                ('freatico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.freatico')),
                ('obrasrecomend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.obras')),
                ('personadiger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.personadiger')),
                ('psicorecomend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.psicos')),
                ('talud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.taludes')),
                ('tipoactiv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.tipoactividad')),
                ('tipodeslizam', models.ManyToManyField(to='Gestion.deslizamiento')),
                ('tipoerosion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.erosion')),
            ],
        ),
        migrations.AddField(
            model_name='taludes',
            name='tipotalud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.tipotalud'),
        ),
    ]
