# Generated by Django 4.2 on 2023-04-13 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoBarrver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='TipoComcorr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='barrver',
            name='comcorr',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='Gestion.comcorr'),
        ),
        migrations.AlterField(
            model_name='comcorr',
            name='id',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='taludes',
            name='observaciones',
            field=models.CharField(max_length=500),
        ),
        migrations.AddField(
            model_name='barrver',
            name='tipo',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='Gestion.tipobarrver'),
        ),
        migrations.AddField(
            model_name='comcorr',
            name='tipo',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='Gestion.tipocomcorr'),
        ),
    ]
