# Generated by Django 4.2 on 2023-04-13 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0002_tipobarrver_tipocomcorr_barrver_comcorr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barrver',
            name='comcorr',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Gestion.comcorr'),
        ),
        migrations.AlterField(
            model_name='comcorr',
            name='id',
            field=models.CharField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comcorr',
            name='tipo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Gestion.tipocomcorr'),
        ),
    ]
