from django.contrib import admin
from models import *

# Register your models here.
admin.site.register(Cez)
admin.site.register(Comcorr)
admin.site.register(Barrver)
admin.site.register(Persona)
admin.site.register(PersonaDiger)
admin.site.register(Geologia)
admin.site.register(Litologia)
admin.site.register(Pendiente)
admin.site.register(Freatico)
admin.site.register(Erosion)
admin.site.register(Deslizamiento)
admin.site.register(ElemExpuestos)
admin.site.register(Afectacion)
admin.site.register(Cobertura)
admin.site.register(Tipoactividad)
admin.site.register(Tipoproceso)
admin.site.register(TipoTalud)
admin.site.register(Tipoclima)
admin.site.register(FactoresContr)
admin.site.register(FactoresDeton)
admin.site.register(Obras)
admin.site.register(Psicos)
admin.site.register(Taludes)