from django.contrib import admin
from Aplicaciones.Gestion.models import *

# Register your models here.
admin.site.register(Cez)
admin.site.register(Comcorr)
admin.site.register(TipoBarrver)
admin.site.register(TipoComcorr)
admin.site.register(Barrver)
admin.site.register(Persona)
admin.site.register(PersonaDiger)
admin.site.register(Geologia)
admin.site.register(Litologia)
admin.site.register(Pendiente)
admin.site.register(Freatico)
admin.site.register(Erosion)
admin.site.register(Deslizamiento)
admin.site.register(ElemExpuestos)
admin.site.register(Afectacion)
admin.site.register(Cobertura)
admin.site.register(TipoActividad)
admin.site.register(TipoProceso)
admin.site.register(TipoTalud)
admin.site.register(TipoClima)
admin.site.register(FactoresContr)
admin.site.register(FactoresDeton)
admin.site.register(Obras)
admin.site.register(Psicos)
admin.site.register(Taludes)